######################## default configuration ####################
baseURL = "https://modernapps.ninja/"
title = "ModernApps by VMware Tanzu Home"
theme = "educenter-hugo"
# themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "modernappsninja" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # desable language from here

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Free Courses with an Active Expert Community powered by VMware Tanzu"
author = "ModernApps Ninja"
# contact info
# address = "9567 Turner Trace Apt. BC C3G8A4"
# mobile = "+211234565523"
email = "modernappsninja@googlegroups.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-162817887-1" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/vmwaretanzu/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/modernappsninja"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/vmware/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/modernappsninja/"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/vmware-tanzu/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 VMware"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "courses"
url = "course"
weight = 5

[[Languages.en.menu.main]]
name = "tutorials"
url = "blog"
weight = 10

[[Languages.en.menu.main]]
name = "guides"
identifier = "guides"
weight = 12

[[Languages.en.menu.main]]
parent = "guides"
name = "Certified Kubernetes Administrator Study Guide"
URL = "https://modernapps.ninja/ckastudyguide_sg2378/docs/"
weight = 1205

[[Languages.en.menu.main]]
parent = "guides"
name = "Tanzu Glossary"
URL = "https://modernapps.ninja/tanzuglossary_tg7721/docs/"
weight = 1207

[[Languages.en.menu.main]]
parent = "guides"
name = "Tanzu Standard Getting Started Guide"
URL = "https://modernapps.ninja/tanzustandardgettingstarted_ts5887/docs/"
weight = 1204

[[Languages.en.menu.main]]
parent = "guides"
name = "Editing with VSCode"
URL = "https://modernapps.ninja/editingwithvscode_pd1400/docs/localdevelopment/"
weight = 1206

[[Languages.en.menu.main]]
name = "events"
url = "event"
weight = 13

[[Languages.en.menu.main]]
name = "Learn More"
identifier = "Learn More"
weight = 15


#[[Languages.en.menu.main]]
#parent = "Learn More"
#name = "Kubernetes and Spring Workshops"
#URL = "https://tanzu.vmware.com/developer/workshops/"
#weight = 1515

[[Languages.en.menu.main]]
parent = "Learn More"
name = "vSphere with Tanzu Tech Zone"
URL = "https://core.vmware.com/tanzu"
weight = 1525

[[Languages.en.menu.main]]
parent = "Learn More"
name = "Kubernetes Courses"
URL = "https://kube.academy/courses"
weight = 1520

[[Languages.en.menu.main]]
parent = "Learn More"
name = "Ask us anything"
URL = "https://github.com/ModernAppsNinja/modernappsninja.github.io/discussions"
weight = 1587

[[Languages.en.menu.main]]
parent = "Learn More"
name = "Tanzu Documentation"
URL = "https://docs.vmware.com/en/VMware-Tanzu/index.html"
weight = 1590

[[Languages.en.menu.main]]
parent = "Learn More"
name = "ModernApps Github Homepage"
URL = "https://github.com/modernappsninja/modernappsninja.github.io/"
weight = 1585


[[Languages.en.menu.main]]
parent = "Learn More"
name = "Workshops and Hands-on Labs"
URL = "./about/labs"
weight = 1522

#[[Languages.en.menu.main]]
#parent = "Learn More"
#name = "Tutorials from the vExpert commnunity"
#URL = "./blog"
#weight = 1510

#[[Languages.en.menu.main]]
#parent = "Learn More"
#name = "Labs"
#URL = "about/labs"
#weight = 3007

#[[Languages.en.menu.main]]
#weight = 3
#name = "Pages"
#hasChildren = true

#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "teacher"
#  url = "teacher"

#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "notice"
#  url = "notice"

#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "event"
#  url = "event"

#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "scholarship"
#  url = "scholarship"

#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "research"
#  url = "research"
  
#[[Languages.en.menu.main]]
#name = "blog"
#url = "blog"
#weight = 4
  
#[[Languages.en.menu.main]]
#name = "Contact"
#url = "contact"
#weight = 5


# footer menu

#[[Languages.en.menu.footer]]
#name = "teacher"
#url = "teacher"

#[[Languages.en.menu.footer]]
#name = "notice"
#url = "notice"

#[[Languages.en.menu.footer]]
#name = "event"
#url = "event"

#[[Languages.en.menu.footer]]
#name = "scholarship"
#url = "scholarship"

#[[Languages.en.menu.footer]]
#name = "research"
#url = "research"



################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; VMware 2021"



################### French navigation ####################

# main menu
[[Languages.fr.menu.main]]
name = "À propos"
url = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Cours"
url = "course"
weight = 2

[[Languages.fr.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Évènement"
  url = "event"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Cursus"
  url = "scholarship"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research"
  
[[Languages.fr.menu.main]]
name = "blog"
url = "blog"
weight = 4
  
[[Languages.fr.menu.main]]
name = "Contact"
url = "contact"
weight = 5


# footer menu

[[Languages.fr.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.fr.menu.footer]]
name = "notice"
url = "notice"

[[Languages.fr.menu.footer]]
name = "event"
url = "event"

[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.fr.menu.footer]]
name = "research"
url = "research"
